services:
  frontend:
    build: ./front-end
    ports:
      - 5173:5173
    volumes:
      - pets-front:/front-end
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    build: ./back-end
    ports:
      - 3000:3000
    links:
      - database
    volumes:
      - pets-back:/back-end
    environment:
      - CHOKIDAR_USEPOLLING=true
  database:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MARIADB_USER=root
      - MARIADB_ROOT_PASSWORD=123
    volumes:
      - pets-data:/var/lib/mysql
volumes:
  pets-data:
  pets-front:
  pets-back: