FROM node:23-alpine3.20

WORKDIR /home/app

COPY . .

RUN yarn add react react-dom react-hook-form boxicons react-router react-router-dom lucide-react @supabase/supabase-js @emailjs/browser sweetalert sweetalert2 framer-motion
RUN yarn add @fullcalendar/core @fullcalendar/react @fullcalendar/daygrid @fullcalendar/interaction @fullcalendar/timegrid @fullcalendar/list
RUN yarn add -D vite @vitejs/plugin-react-swc sass-embedded

EXPOSE 5173

CMD ["yarn", "vite"]
