services:
  backApp:
    build: .
    ports:
      - 3000:3000
    links:
      - database
  database:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=123
      - MARIADB_USER=root
